name: Java Build and Docker Deploy

on:
  push:
    branches:
      - fea/payment

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Check Java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Build JAR
        run: mvn clean package

      - name: Check JAR File
        run: ls -l target/

      - name: Build Docker Image
        run: docker build -t my-java-app:latest .

      - name: Stop and Remove Old Container
        run: docker rm -f my-java-container || true

      - name: Run New Container
        run: |
          docker run -d \
            --name my-java-container \
            -p 8080:8080 \
            my-java-app:latest

      - name: Check Running Container
        run: docker ps
