name: Java CI Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t myapp:1.0 .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name myapp myapp:1.0

      - name: Test application
        run: |
          sleep 15
          curl http://localhost:8080
