name: Java CI Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-docker:

    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Build JAR
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t myapp:1.0 .

      - name: Run Docker container
        run: |
          docker rm -f myapp || true
          docker run -d \
            --name myapp \
            -p 8080:8080 \
            myapp:1.0

      - name: Check Docker container
        run: docker ps

      
